name: Deploy WAR File to Tomcat

on:
  push:
    branches:
      - '**'  # Trigger on any branch push
    paths:
      - '**/*.war'  # Trigger only when a .war file is pushed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Check for WAR file
      - name: Check for WAR file
        run: |
          if ls *.war 1> /dev/null 2>&1; then
            echo "WAR file found"
          else
            echo "No WAR file found. Exiting."
            exit 1

      # Step 3: Set up SSH connection
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

      # Step 4: Deploy WAR to Tomcat
      - name: Deploy WAR to Tomcat
        run: |
          scp -o StrictHostKeyChecking=no *.war ubuntu@52.55.90.31:/home/ubuntu/apache-tomcat-10.1.34/webapps/
          ssh -o StrictHostKeyChecking=no ubuntu@52.55.90.31 << 'EOF'
            cd /home/ubuntu/apache-tomcat-10.1.34
            ./bin/shutdown.sh
            ./bin/startup.sh
          EOF
