name: Deploy WAR File to Tomcat

on:
  push:
    branches:
      - '**'  # Trigger on any branch push
    paths:
      - '**/*.war'  # Trigger only when a .war file is pushed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set WAR_FILE variable to the WAR file found in the repository
      - name: Set WAR file variable
        run: |
          export WAR_FILE=$(find . -name '*.war' | head -n 1)
          echo "WAR file is: $WAR_FILE"
        id: set_war_file
