name: Deploy WAR File to Tomcat

on:
  push:
    branches:
      - '**'  # Trigger on any branch push
    paths:
      - '**/*.war'  # Trigger only when a .war file is pushed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set WAR_FILE variable to the WAR file found in the repository
      - name: Set WAR file variable
        run: |
          export WAR_FILE=$(find . -name '*.war' | head -n 1)
          echo "WAR file is: $WAR_FILE"
        id: set_war_file

      # Step 3: Check if a WAR file is found
      - name: Check for WAR file
        run: |
          if [ -z "$WAR_FILE" ]; then
            echo "No WAR file found. Exiting."
            exit 1
          else
            echo "Found WAR file: $WAR_FILE"
          fi

      # Step 4: Set up SSH connection
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

      # Step 5: Deploy WAR file to Tomcat
      - name: Deploy WAR to Tomcat
        run: |
          echo "Deploying WAR file: $WAR_FILE"
          scp -o StrictHostKeyChecking=no "$WAR_FILE" ubuntu@52.55.90.31:/home/ubuntu/apache-tomcat-10.1.34/webapps/
          ssh -o StrictHostKeyChecking=no ubuntu@52.55.90.31 << 'EOF'
            cd /home/ubuntu/apache-tomcat-10.1.34
            ./bin/shutdown.sh
            ./bin/startup.sh
            ls -l /home/ubuntu/apache-tomcat-10.1.34/webapps/
          EOF
