name: Deploy WAR File to Tomcat

on:
  push:
    branches:
      - '**'  # Trigger on any branch push
    paths:
      - '**/*.war'  # Trigger only when a .war file is pushed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set WAR file variable and debug
      - name: Set WAR file variable
        run: |
          echo "Listing files in the current directory:"
          ls -al
          WAR_FILE=$(find . -name 'sample.war' | head -n 1)
          echo "WAR file found: $WAR_FILE"
          echo "WAR_FILE=$WAR_FILE" >> $GITHUB_ENV

      # Step 3: Check if WAR file is found
      - name: Check if WAR file exists
        run: |
          if [ -z "$WAR_FILE" ]; then
            echo "No WAR file found. Exiting."
            exit 1
          fi

      # Step 4: Set up SSH connection
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

      # Step 5: Deploy WAR to Tomcat
      - name: Deploy WAR to Tomcat
        run: |
          echo "Deploying WAR file: $WAR_FILE"
          scp -o StrictHostKeyChecking=no "$WAR_FILE" ubuntu@52.55.90.31:/home/ubuntu/apache-tomcat-10.1.34/webapps/
          ssh -o StrictHostKeyChecking=no ubuntu@52.55.90.31 << 'EOF'
            cd /home/ubuntu/apache-tomcat-10.1.34
            ./bin/shutdown.sh
            ./bin/startup.sh
            ls -l /home/ubuntu/apache-tomcat-10.1.34/webapps/
          EOF
